package com.silva021.sorteio.home.domain

object RaffleFactory {
    val listRaffle = listOf(
        Raffle(title = "Regina", participant = null),
        Raffle(title = "Débora", participant = null),
        Raffle(title = "Tereza", participant = null),
        Raffle(title = "Aurea", participant = null),
        Raffle(title = "Elvira", participant = null),
        Raffle(title = "Isabel", participant = null),
        Raffle(title = "Margarida", participant = null),
        Raffle(title = "Isaura", participant = null),
        Raffle(title = "Selma", participant = null),
        Raffle(title = "Dulce", participant = null),
        Raffle(title = "Zoiraide", participant = null),
        Raffle(title = "Raquel", participant = null),
        Raffle(title = "Adriana", participant = null),
        Raffle(title = "Simone", participant = null),
        Raffle(title = "Lourdes", participant = null),
        Raffle(title = "Dolores", participant = null),
        Raffle(title = "Roberta", participant = null),
        Raffle(title = "Dirce", participant = null),
        Raffle(title = "Norma", participant = null),
        Raffle(title = "Daniela", participant = null),
        Raffle(title = "Rosália", participant = null),
        Raffle(title = "Joelma", participant = null),
        Raffle(title = "Glória", participant = null),
        Raffle(title = "Fátima", participant = null),
        Raffle(title = "Zuleika", participant = null),
        Raffle(title = "Jurema", participant = null),
        Raffle(title = "Monica", participant = null),
        Raffle(title = "Helena", participant = null),
        Raffle(title = "Eugẽnia", participant = null),
        Raffle(title = "Adelaide", participant = null),
        Raffle(title = "Denise", participant = null),
        Raffle(title = "Jandira", participant = null),
        Raffle(title = "Rosana", participant = null),
        Raffle(title = "Valéria", participant = null),
        Raffle(title = "Celeste", participant = null),
        Raffle(title = "Olinda", participant = null),
        Raffle(title = "Emília", participant = null),
        Raffle(title = "Jaqueline", participant = null),
        Raffle(title = "Adélia", participant = null),
        Raffle(title = "Patricia", participant = null),
        Raffle(title = "Miriam", participant = null),
        Raffle(title = "Clarice", participant = null),
        Raffle(title = "Aurora", participant = Participant("Lucas", "+ 55 21 995999584")),
        Raffle(title = "Linice", participant = null),
        Raffle(title = "Solange", participant = null),
        Raffle(title = "Ivone", participant = null),
        Raffle(title = "Márcia", participant = null),
        Raffle(title = "Dora", participant = null),
        Raffle(title = "Graziela", participant = null),
        Raffle(title = "Maria", participant = null),
    )

    val listRaffleTwo = listOf(
        Raffle(title = "Jaqueline", participant = null),
        Raffle(title = "Adélia", participant = null),
        Raffle(title = "Patricia", participant = null),
        Raffle(title = "Miriam", participant = null),
        Raffle(title = "Clarice", participant = null),
        Raffle(title = "Aurora", participant = Participant("Lucas", "+ 55 21 995999584")),
        Raffle(title = "Linice", participant = null),
        Raffle(title = "Solange", participant = null),
        Raffle(title = "Ivone", participant = null),
        Raffle(title = "Márcia", participant = null),
        Raffle(title = "Dora", participant = null),
        Raffle(title = "Graziela", participant = null),
        Raffle(title = "Maria", participant = null),
    )
}