package com.silva021.sorteio.home.domain.model

object RaffleFactory {
    val listRaffle = listOf(
        Raffle(title = "Regina", participant = null),
        Raffle(title = "Débora", participant = null),
        Raffle(title = "Tereza", participant = Participant("Wesley", null)),
        Raffle(title = "Aurea", participant = Participant("Neves", null)),
        Raffle(title = "Elvira", participant = Participant("Brazilia", null)),
        Raffle(title = "Isabel", participant = Participant("Davi", null)),
        Raffle(title = "Margarida", participant = Participant("Egildo", null)),
        Raffle(title = "Isaura", participant = null),
        Raffle(title = "Selma", participant = null),
        Raffle(title = "Dulce", participant = Participant("Dam", null)),
        Raffle(title = "Zoiraide", participant = Participant("Lucas", null)),
        Raffle(title = "Raquel", participant = null),
        Raffle(title = "Adriana", participant = Participant("Adriana", null)),
        Raffle(title = "Simone", participant = Participant("Mateus Carvalho", null)),
        Raffle(title = "Lourdes", participant = null),
        Raffle(title = "Dolores", participant = Participant("Sogro", null)),
        Raffle(title = "Roberta", participant = Participant("Davi", null)),
        Raffle(title = "Dirce", participant = Participant("Diego", null)),
        Raffle(title = "Norma", participant = Participant("Leonardo Porto", null)),
        Raffle(title = "Daniela", participant = Participant("Neves", null)),
        Raffle(title = "Rosália", participant = null),
        Raffle(title = "Joelma", participant = null),
        Raffle(title = "Glória", participant = null),
        Raffle(title = "Fátima", participant = null),
        Raffle(title = "Zuleika", participant = Participant("Leonardo Porto", null)),
        Raffle(title = "Jurema", participant = Participant("Glauber", null)),
        Raffle(title = "Monica", participant = null),
        Raffle(title = "Helena", participant = Participant("Sergio", null)),
        Raffle(title = "Eugẽnia", participant = Participant("Joshua", null)),
        Raffle(title = "Adelaide", participant = null),
        Raffle(title = "Denise", participant = Participant("Ivanilse", null)),
        Raffle(title = "Jandira", participant = null),
        Raffle(title = "Rosana", participant = Participant("Marcos (ETESC)", null)),
        Raffle(title = "Valéria", participant = null),
        Raffle(title = "Celeste", participant = Participant("Sergio", null)),
        Raffle(title = "Olinda", participant = Participant("Sandra", null)),
        Raffle(title = "Emília", participant = null),
        Raffle(title = "Jaqueline", participant = null),
        Raffle(title = "Adélia", participant = null),
        Raffle(title = "Patricia", participant = null),
        Raffle(title = "Miriam", participant = null),
        Raffle(title = "Clarice", participant = Participant("Maria", null)),
        Raffle(title = "Aurora", participant = Participant("", "+ 55 21 995999584")),
        Raffle(title = "Lenice", participant = Participant("Vander", null)),
        Raffle(title = "Solange", participant = Participant("Davi", null)),
        Raffle(title = "Ivone", participant = Participant("Joshua", null)),
        Raffle(title = "Márcia", participant = Participant("Jose Julio", null)),
        Raffle(title = "Dora", participant = Participant("Elias", null)),
        Raffle(title = "Graziela", participant = null),
        Raffle(title = "Maria", participant = Participant("Keliane", null))
    )

    val listRaffleTwo = listOf(
        Raffle(title = "Regina", participant = null),
        Raffle(title = "Débora", participant = Participant("Bia", null)),
        Raffle(title = "Tereza", participant = null),
        Raffle(title = "Aurea", participant = null),
        Raffle(title = "Elvira", participant = null),
        Raffle(title = "Isabel", participant = null),
        Raffle(title = "Margarida", participant = null),
        Raffle(title = "Isaura", participant = null),
        Raffle(title = "Selma", participant = Participant("Sandra", null)),
        Raffle(title = "Dulce", participant = Participant("Keiliane", null)),
        Raffle(title = "Zoiraide", participant = Participant("Lucas", null)),
        Raffle(title = "Raquel", participant = Participant("Andre", null)),
        Raffle(title = "Adriana", participant = Participant("João", null)),
        Raffle(title = "Simone", participant = Participant("Mateus Carvalho", null)),
        Raffle(title = "Lourdes", participant = null),
        Raffle(title = "Dolores", participant = Participant("Sogro", null)),
        Raffle(title = "Roberta", participant = null),
        Raffle(title = "Dirce", participant = Participant("Leonardo Porto", null)),
        Raffle(title = "Norma", participant = null),
        Raffle(title = "Daniela", participant = Participant("Neves", null)),
        Raffle(title = "Rosália", participant = null),
        Raffle(title = "Joelma", participant = Participant("Lucia", null)),
        Raffle(title = "Glória", participant = Participant("Vasco Filiphe", null)),
        Raffle(title = "Fátima", participant = Participant("Andre", null)),
        Raffle(title = "Zuleika", participant = Participant("Leo FP", null)),
        Raffle(title = "Jurema", participant = Participant("Leonardo Porto", null)),
        Raffle(title = "Monica", participant = null),
        Raffle(title = "Helena", participant = Participant("Naype", null)),
        Raffle(title = "Eugẽnia", participant = null),
        Raffle(title = "Adelaide", participant = Participant("Larissa", null)),
        Raffle(title = "Denise", participant = null),
        Raffle(title = "Jandira", participant = null),
        Raffle(title = "Rosana", participant = Participant("Gisele", null)),
        Raffle(title = "Valéria", participant = null),
        Raffle(title = "Celeste", participant = Participant("Elias", null)),
        Raffle(title = "Olinda", participant = null),
        Raffle(title = "Emília", participant = Participant("Neves", null)),
        Raffle(title = "Jaqueline", participant = null),
        Raffle(title = "Adélia", participant = Participant("Maria", null)),
        Raffle(title = "Patricia", participant = null),
        Raffle(title = "Miriam", participant = Participant("Guilherme Ferreira", null)),
        Raffle(title = "Clarice", participant = null),
        Raffle(title = "Aurora", participant = null),
        Raffle(title = "Linice", participant = null),
        Raffle(title = "Solange", participant = null),
        Raffle(title = "Ivone", participant = null),
        Raffle(title = "Márcia", participant = null),
        Raffle(title = "Dora", participant = null),
        Raffle(title = "Graziela", participant = Participant("Gilceia", null)),
        Raffle(title = "Maria", participant = Participant("Eline", null))
    )
}