package com.silva021.sorteio.home.domain.model

object RaffleFactory {
    val listRaffle = listOf(
        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Regina"),
        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Débora"),
        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Tereza", participantName = "Wesley", participantContact = null),
        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Aurea", participantName ="Neves"),
        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Elvira", participantName ="Brazilia"),
        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Isabel", participantName = "Davi"),
        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Margarida", participantName = "Egildo"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Isaura"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Selma"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Dulce", participantName ="Dam"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Zoiraide", participantName ="Lucas"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Raquel"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Adriana", participantName ="Adriana"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Simone", participantName ="Mateus Carvalho"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Lourdes"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Dolores", participantName ="Sogro"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Roberta", participantName ="Davi"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Dirce",  participantName ="Diego"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Norma",  participantName ="Leonardo Porto"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Daniela", participantName ="Neves"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Rosália"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Joelma"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Glória"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Fátima"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Zuleika",participantName ="Leonardo Porto"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Jurema",    participantName ="Glauber"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Monica"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Helena",    participantName ="Sergio"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Eugẽnia", participantName ="Joshua"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Adelaide"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Denise", participantName ="Ivanilse"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Jandira"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Rosana", participantName ="Marcos (ETESC)"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Valéria"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Celeste", participantName ="Sergio"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Olinda", participantName ="Sandra"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Emília"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Jaqueline"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Adélia"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Patricia"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Miriam"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Clarice",participantName ="Maria"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Aurora",),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Lenice", participantName ="Vander"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Solange", participantName ="Davi"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Ivone", participantName ="Joshua"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Márcia", participantName ="Jose Julio"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Dora",participantName ="Elias"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Graziela"),
//        Raffle(raffleType = RaffleType.RAFFLE_ONE.name, title = "Maria", participantName ="Keliane")
    )

    val listRaffleTwo = listOf(
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Regina"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Débora", participantName = "Bia"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Tereza"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Aurea"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Elvira"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Isabel"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Margarida"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Isaura"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Selma", participantName = "Sandra"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Dulce", participantName ="Keiliane"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Zoiraide", participantName ="Lucas"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Raquel", participantName = "Andre"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Adriana", participantName ="João"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Simone", participantName ="Mateus Carvalho"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Lourdes"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Dolores", participantName ="Sogro"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Roberta"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Dirce",  participantName ="Leonardo Porto"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Norma"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Daniela", participantName ="Neves"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Rosália"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Joelma", participantName ="Lucia"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Glória", participantName ="Vasco Filiphe"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Fátima", participantName ="Andre"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Zuleika",participantName ="Leo FP"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Jurema",    participantName ="Leonardo Porto"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Monica"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Helena",    participantName ="Naype"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Eugẽnia"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Adelaide", participantName = "Larissa"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Denise"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Jandira"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Rosana", participantName ="Gisele"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Valéria"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Celeste", participantName ="Elias"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Olinda"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Emília", participantName = "Neves"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Jaqueline"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Adélia", participantName = "Maria"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Patricia"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Miriam",participantName ="Maria"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Clarice"),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Aurora",),
//        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Lenice"),
        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Solange"),
        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Ivone"),
        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Márcia"),
        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Dora"),
        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Graziela" ,participantName ="Gilceia"),
        Raffle(raffleType = RaffleType.RAFFLE_TWO.name, title = "Maria", participantName ="Eline")
    )
}